### PR TITLE
Updating to .NET Standard, updating to use latest version of Cake.

### PR DESCRIPTION
**Pull request by zbeer**

### CODE REVIEW

**Comment by zbeer** [comment]
I still need to remove all instances of AzureZ before this can be merged.

**Comment by zbeer** [comment]
@gep13:  Is it safe for me to ignore the AppVeyor error above and that you'll be addressing that as part of the changes you intend to do?

**Comment by zbeer** [comment]
@gep13:  Conversely, can I get access to AppVeyor to alter it's behavior?  It's expecting to run MSBuild on the solution file.  It should instead be calling the Cake script.

**Comment by gep13** [comment]
@zbeer you can safely ignore the AppVeyor warnings/errors.

Once everything is setup, you will have access to AppVeyor, yes.  However, one of the things I will be doing will be to add an `.appveyor.yml` file into the repository, which is where almost all of the configuration will reside.

**Comment by gep13** [comment]
@zbeer is this now ready for review?

**Comment by zbeer** [comment]
@gep13:  Outstanding.  Yup - ready for review!

**Comment by gep13** [comment]
@zbeer perfect, I will action this as soon as possible.  Thanks for your co-operation in switching to this repository.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@zbeer your changes have been merged, thanks for your contribution 👍

**Pull request merged**
